name: ocvalidate
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.auth'
      - '**.gitignore'
  workflow_dispatch:
jobs:
  test-configs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: brokeyourbike/ocvalidate-action@v0.3
        with:
          opencore-version: '0.9.4'
          release: true

      - run: |
          ocvalidate "EFI/OC/config.plist" || exit 1
